// src/app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  // Use your production domain so relative URLs (e.g. OG) resolve correctly
  metadataBase: new URL('https://martinenke.vercel.app'),
  

  title: {
    default: 'Martin Enke — Full-stack & GenAI Engineer',
    template: '%s — Martin Enke',
  },
  description:
    'Backend & GenAI engineer integrating LLMs into real products. Python · FastAPI/Flask · React · TypeScript · SQL/PostgreSQL.',

  openGraph: {
    type: 'website',
    url: '/',              // resolved against metadataBase → https://martinenke.vercel.app/
    siteName: 'Martin Enke — Portfolio',
    // No images here: your src/app/opengraph-image.tsx already generates them.
  },

  twitter: {
    card: 'summary_large_image',
    // No images needed; Twitter will use the same OG image generated by opengraph-image.tsx
  },

  icons: { icon: [{ url: '/favicon.png?v=3', type: 'image/png' }] },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 text-slate-100 antialiased">
        {children}
      </body>
    </html>
  )
}
